config/routes.rb
OmniauthDemo::Application.routes.draw do

  #get "tag/index"

  require 'resque/server'

  authenticate 'user' do
    mount Resque::Server.new, :at => '/resque'
  end

  resources :tags, :only => [ :index ]

  resources :ticket_updates, :priorities

  resources :ticket_owners

  resources :ticket_codes

  resources :ticket_categories

  resources :site_configs, :except => [ :new, :create, :destroy, :show ]

  Mercury::Engine.routes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
  end
  
  resources :users, :only => [ :index, :show, :edit, :update, :destroy ] do
    collection do
      get :search
      get :table
    end
    resources :tickets, :except => [ :edit ]
  end

  resources :documents, :path => 'files' do
    member do
      get :download
    end
    collection do
      get :search
      get :table
    end
  end

  resources :case_studies do
    collection do
      get :added
      get :updated
      get :search
      get :table
    end
    member do
      post :mercury_update
    end
  end

  resources :imports do
    member do
      get 'process_yaml'
    end
  end

  resources :languages

  resources :libraries do
    member do
      get :download
      get :podcast, :as => :podcast, :defaults => { :format => 'xml' }
    end
    collection do
      get :search
    end
  end

  resources :stacks, :only => [ :index, :new, :create, :destroy ]

  resources :photos do
    collection do
      get :search
    end
    member do
      get :embed
    end
  end

  resources :sites, :sectors, :positions, :jobs, :staff, :websites, :identities, :stages, :scopes, :regiontypes, :pc_regions, :regions, :volunteers, :moments

  resources :blogs do
    collection do
      get :updated
    end
  end

  resources :feedback, :except => [:edit, :update] do
    collection do
      get :volunteer_request
    end
  end

  resources :contributions, :only => [ :index, :new, :create, :destroy ]

  resources :permissions, :only => [ :index, :new, :create, :destroy ]

  resources :pages do
    collection do
      get :updated
      get :added
      get :popular
      get :ajax
      get :search
      get :feed, :as => :feed, :defaults => { :format => 'atom' }
      get :table
    end
    member do
      post :mercury_update
    end
  end

  match '/disclaimer', :to => 'statics#disclaimer', :as => :disclaimer
  match '/privacy', :to => 'statics#privacy', :as => :privacy_policy
  match '/security', :to => 'statics#security', :as => :security
  match '/about_us', :to => 'statics#about_us', :as => :about
  match '/splash', :to => 'statics#splash', :as => :splash
  match '/help', :to => 'statics#help', :as => :help
  match '/search', :to => 'statics#search', :as => :search
  match '/welcome', :to => 'statics#welcome', :as => :entry
  match '/goodbye', :to => 'statics#goodbye', :as => :exit
  match '/dashboard', :to => 'statics#dashboard', :as => :dashboard
  match '/timeline', :to => 'statics#timeline', :as => :timeline

  match '/feedback', :to => 'feedback#new'
  match '/feed/pages', :to => 'pages#updated'
  
  match '/facebook' => redirect('https://apps.facebook.com/peacecorps')
  match '/youtube' => redirect('https://www.youtube.com/pcsenegaladmin')
  match '/twitter' => redirect('http://twitter.com/#!/pc_senegal')
    
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'statics#splash'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_country_field.html.haml
- if can? :manage, object
  .field
    = f.label :country, 'Country*'
    = f.country_select(:country, ['SN', 'GM'])
    -#= f.collection_select(:country, Carmen.countries)
- else
  = f.hidden_field(:country, :value => current_user.country)

app/views/shared/_form_error.html.haml
- error ||= a
- if error.errors.any?
  .alert.alert-error
    %h4= #{pluralize(error.errors.count, "error")} prohibited this object from being saved:
    - error.errors.full_messages.each do |msg|
      %p= msg

app/views/shared/_google_analytics.html.erb
<% unless user_signed_in? && (current_user.role?(:admin) || current_user.role?(:moderator)) %>
	<script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', '<%= ENV['G_ANALYTICS_ID'] %>']);
	  _gaq.push(['_setDomainName', '<%= request.host %>']);
	  _gaq.push(['_setAllowLinker', true]);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
<% end %>

app/views/shared/_menu.html.haml
.left-v-menu
  %div{:style => 'margin-right:10px;'}
    - if signed_in?
      - if current_user.beta?
        .alert.alert-warning
          %h4.alert-heading You're a beta user!
          %p You'll see some experimental features around the site; if you don't like them, talk to Jack.
      - if current_user.pc?
        - percent = REDIS.hget("users:#{(current_user.role?(:admin) && @user) ? @user.id : current_user.id}:stats", 'perc_profile') || 0
        = render 'shared/percentages', :percent => percent if percent.to_i < 100 && percent.to_i > 5
      
  %h3
    = flag_icon(cookies[:country].downcase)
    = Carmen.country_name(cookies[:country])
  %ul.nav.nav-list
    - if @page && !@page.new_record? && @page.children.accessible_by(current_ability).any?
      %li.nav-header= @page.title.upcase
      - if @page.parent && can?(:read, @page.parent)
        %li
          = link_to @page.parent do
            %i.icon-chevron-up
            go back up
      - Page.where(:parent_id => @page.id).order("#{@page.sort_by ? @page.sort_by : 'title'} #{@page.sort_order ? @page.sort_order : 'ASC'}").each do |item|
        %li
          = link_to item.title, item, :class => 'tooltip-right-slow', :title => item.description
      %hr
    -elsif @page && !@page.new_record? && @page.parent && @page.siblings.accessible_by(current_ability).any?
      %li.nav-header= @page.parent.title.upcase
      - if @page.parent && can?(:read, @page.parent)
        %li
          = link_to @page.parent do
            %i.icon-chevron-up
            go back up
      - Page.where(:parent_id => @page.parent_id).order("#{@page.parent.sort_by ? @page.parent.sort_by : 'title'} #{@page.parent.sort_order ? @page.parent.sort_order : 'ASC'}").each do |item|
        %li
          = link_to item.title, item, :class => 'tooltip-right-slow', :title => item.description
    %li.nav-header Browse
    - Page.accessible_by(current_ability).order('title ASC').where("parent_id IS NULL AND country = ?", cookies[:country]).each do |item|
      %li
        = link_to item.title, item, :class => 'tooltip-right-slow', :title => item.description
    - if Page.unscoped.tagged_with('quicklink').order('title').any?
      %li.nav-header Quick Links
      - Page.unscoped.tagged_with('quicklink').order('title').each do |link|
        %li= link_to link.canonical_title, link if can? :read, link
  %ul.nav.nav-list.visible-desktop
    %li.nav-header Resources
    - if user_signed_in?
      %li
        = link_to entry_path, :class => 'tooltip-right-slow', :title => "List of the latest features. If you've forgotten about something, check here first." do
          %i.icon-star
          Welcome
      %li
        = link_to dashboard_path, :class => 'tooltip-right-slow', :title => "An overview of the various resources on the site, and what's been changing." do
          %i.icon-home
          Dashboard
    %li
      = link_to timeline_path, :class => 'tooltip-right-slow', :title => 'Stories, photos and videos shared by 50 years of Peace Corps Senegal Volunteers.' do
        %i.icon-time
        50th Anniversary Timeline
    %li
      = link_to case_studies_path, :class => 'tooltip-right-slow', :title => 'Documentation of projects past and present, successes and failures.' do
        %i.icon-road
        Case Studies
    %li
      = link_to updated_pages_path, :class => 'tooltip-right-slow', :title => 'Presentation content. Info about what we do, and how we do it.' do
        %i.icon-list-alt
        Content
    %li
      = link_to documents_path, :class => 'tooltip-right-slow', :title => 'Get the latest and greatest information, podcasts, and radio shows.' do
        %i.icon-file
        Files
    %li
      = link_to libraries_path, :class => 'tooltip-right-slow', :title => 'View collections put together by users, highlighting favorite or useful items.' do
        %i.icon-book
        Libraries
    %li
      = link_to photos_path, :class => 'tooltip-right-slow', :title => 'Browse Volunteer photos, or upload your own.' do
        %i.icon-picture
        Photos
    -#%li= link_to videos_path do
      %i.icon-film
      Videos
    %li
      = link_to( { :controller => 'staff', :action => 'index' }, :class => 'tooltip-right-slow', :title => 'Get to know our staff.') do
        %i.icon-user
        Staff
    %li
      = link_to users_path, :class => 'tooltip-right-slow', :title => "Take a look at who's on the site." do
        %i.icon-user
        Users
    %li
      = link_to volunteers_path, :class => 'tooltip-right-slow', :title => 'Get to know our Volunteers.' do
        %i.icon-user
        Volunteers
    %li
      = link_to '/search', :class => 'tooltip-right-slow', :title => "Still can't find it? Search within our site using the power of Google." do
        %i.icon-search
        Google Search

app/views/shared/_modal_standard.html.haml
- title ||= nil
- body ||= nil
- footer ||= nil
.modal.modal-standard.hide{:id => id}
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h3= title
  .modal-body
    = body
  .modal-footer
    = footer

app/views/shared/_notice_bar.html.haml
.container#notice
  .row
    .span-24.last
      %p= notice

app/views/shared/_percentages.html.haml
- if percent.to_i > 80
  .alert.alert-success Almost there! You're profile is #{percent}% finished! Go to your #{link_to 'profile', current_user} to add the final pieces!
  .progress.progress-striped.progress-success
    .bar{:style => "width:#{percent}%"}
- elsif percent.to_i > 60
  .alert.alert-warning Oh no! Your profile is sadly incomplete! You're only #{percent}% finished! Go to your #{link_to 'profile', current_user} to get it up to snuff!
  .progress.progress-striped.progress-warning
    .bar{:style => "width:#{percent}%"}
- else
  .alert.alert-danger Whoa, what have you been doing? Finish your profile! It's only #{percent}% filled out!
  .progress.progress-striped.progress-danger
    .bar{:style => "width:#{percent}%"}

app/views/shared/_podcast.xml.erb
<title><%= @title %></title>
<link><%= @link %></link>
<language><%= @language %></language>
<copyright><%= @copyright %></copyright>
<itunes:subtitle><%= @subtitle %></itunes:subtitle>
<itunes:author><%= @author %></itunes:author>
<description><%= @description %></description>
<itunes:owner>
	<itunes:name><%= @itunes_name %></itunes:name>
	<itunes:email><%= @itunes_email %></itunes:email>
</itunes:owner>
<itunes:image href="<%= @image %>" />
<itunes:category text="Education"></itunes:category>
<itunes:explicit>clean</itunes:explicit>

app/views/shared/_slide.html.haml
.item
  = image_tag slide[:photo]
  .carousel-caption
    %h1= slide[:title]
    = truncate(slide[:text], :length => 100, :separator => ' ')
    = link_to 'read more', slide[:path]
    &rang;

app/views/shared/_slider.html.haml
.carousel#splash_carousel
  .carousel-inner
    - slides.each do |slide|
      = render 'shared/slide', :slide => slide
  %a.carousel-control.left{'href' => '#splash_carousel', 'data-slide' => 'prev'} &lsaquo;
  %a.carousel-control.right{'href' => '#splash_carousel', 'data-slide' => 'next'} &lsaquo;

app/views/shared/_tag_cloud.html.haml
.tags{:style => 'text-align:justify;'}
  - tag_cloud(tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class|
    = link_to tag.name, model.tagged_with(tag).first, :class => css_class
.clearfloat

app/views/shared/_tag_field.html.haml
.field
  = f.label :tag_list, 'Tag it! (comma-separated)'
  = f.text_field :tag_list

app/views/shared/_tags.html.haml
- tags.each do |tag|
  = render 'shared/tag', :tag => tag

app/views/shared/_zopim.html.erb
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?Tdz9iFSCZ89EUS0e08LNCeby66lzNdV4';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->