config/routes.rb
OmniauthDemo::Application.routes.draw do

  #get "tag/index"

  require 'resque/server'

  authenticate 'user' do
    mount Resque::Server.new, :at => '/resque'
  end

  resources :tags, :only => [ :index ]

  resources :ticket_updates, :priorities

  resources :ticket_owners

  resources :ticket_codes

  resources :ticket_categories

  resources :site_configs, :except => [ :new, :create, :destroy, :show ]

  Mercury::Engine.routes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
  end
  
  resources :users, :only => [ :index, :show, :edit, :update, :destroy ] do
    collection do
      get :search
      get :table
    end
    resources :tickets, :except => [ :edit ]
  end

  resources :documents, :path => 'files' do
    member do
      get :download
    end
    collection do
      get :search
      get :table
    end
  end

  resources :case_studies do
    collection do
      get :added
      get :updated
      get :search
      get :table
    end
    member do
      post :mercury_update
    end
  end

  resources :imports do
    member do
      get 'process_yaml'
    end
  end

  resources :languages

  resources :libraries do
    member do
      get :download
      get :podcast, :as => :podcast, :defaults => { :format => 'xml' }
    end
    collection do
      get :search
    end
  end

  resources :stacks, :only => [ :index, :new, :create, :destroy ]

  resources :photos do
    collection do
      get :search
    end
    member do
      get :embed
    end
  end

  resources :sites, :sectors, :positions, :jobs, :staff, :websites, :identities, :stages, :scopes, :regiontypes, :pc_regions, :regions, :volunteers, :moments

  resources :blogs do
    collection do
      get :updated
    end
  end

  resources :feedback, :except => [:edit, :update] do
    collection do
      get :volunteer_request
    end
  end

  resources :contributions, :only => [ :index, :new, :create, :destroy ]

  resources :permissions, :only => [ :index, :new, :create, :destroy ]

  resources :pages do
    collection do
      get :updated
      get :added
      get :popular
      get :ajax
      get :search
      get :feed, :as => :feed, :defaults => { :format => 'atom' }
      get :table
    end
    member do
      post :mercury_update
    end
  end

  match '/disclaimer', :to => 'statics#disclaimer', :as => :disclaimer
  match '/privacy', :to => 'statics#privacy', :as => :privacy_policy
  match '/security', :to => 'statics#security', :as => :security
  match '/about_us', :to => 'statics#about_us', :as => :about
  match '/splash', :to => 'statics#splash', :as => :splash
  match '/help', :to => 'statics#help', :as => :help
  match '/search', :to => 'statics#search', :as => :search
  match '/welcome', :to => 'statics#welcome', :as => :entry
  match '/goodbye', :to => 'statics#goodbye', :as => :exit
  match '/dashboard', :to => 'statics#dashboard', :as => :dashboard
  match '/timeline', :to => 'statics#timeline', :as => :timeline

  match '/feedback', :to => 'feedback#new'
  match '/feed/pages', :to => 'pages#updated'
  
  match '/facebook' => redirect('https://apps.facebook.com/peacecorps')
  match '/youtube' => redirect('https://www.youtube.com/pcsenegaladmin')
  match '/twitter' => redirect('http://twitter.com/#!/pc_senegal')
    
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'statics#splash'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/document.rb
class Document < ActiveRecord::Base

  require 'mp3info'

  # main document
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_content_type :file, :content_type => [
    'audio/mpeg',
    'audio/mp3',
    'application/pdf',
    'text/plain',
    'text/csv',
    'text/xml',
    'text/html',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.oasis.opendocument.presentation',
    'application/vnd.ms-excel',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation', 
    'application/vnd.google-earth.kml+kml', 
    'application/x-latex',
    'application/x-shockwave-flash',
    'application/atom+xml',
    'application/rss+xml',
    'application/xhtml+xml'
  ]

  # source file for document, for archiving
  has_attached_file :source
  validates_attachment_content_type :source, :content_type => [
    'text/plain', 
    'text/csv', 
    'text/xml', 
    'text/html', 
    'application/vnd.ms-excel', 
    'application/vnd.ms-powerpoint', 
    'application/vnd.google-earth.kml+kml',
    'application/x-latex', 
    'application/x-shockwave-flash',
    'application/zip',
    'application/x-gzip',
    'text/vcard',
    'application/msword',
    'application/vnd.ms-excel',
    'application/vnd.ms-powerpoint',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.oasis.opendocument.presentation',
    'application/vnd.oasis.opendocument.graphics', 
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation'
  ]
  
  acts_as_taggable_on :tags

  belongs_to :user
  belongs_to :language
  
  has_many :stacks, :as => :stackable, :dependent => :destroy
  has_many :libraries, :through => :stacks
  
  has_and_belongs_to_many :roles

  accepts_nested_attributes_for :stacks
  
  validates :name, :user_id, :country, :presence => true
  validates :file_fingerprint, :presence => true, :uniqueness => true
  validates :source_fingerprint, :uniqueness => true, :if => "source_file_name"
  validates :source_fingerprint, :presence => true, :if => "source_file_name"

  before_validation :clear_empty_attrs
  before_save :run_before_save
  after_save :run_after_save
  after_commit :asynch_create_zip

  def canonical_title
    self.name
  end

  def formatted_audio_length
    if audio_length
      "#{audio_length.to_i / 3600}:#{sprintf("%02.f", audio_length.to_i / 60)}:#{sprintf("%02.f", audio_length.to_i - 60 * (audio_length.to_i / 60))}"
    end
  end

  def to_param
    "#{id}-#{canonical_title.parameterize}"
  end

  def asynch_create_zip
    for stack in self.stacks do
      Resque.enqueue(Library, stack.library_id)
    end
  end
  
  private

    def clear_empty_attrs
      @attributes.each do |key,value|
        self[key] = nil if value.blank?
      end
      self.name = self.file_file_name if name.nil?
    end

    def run_after_save
      if roles.empty?
        roles << Role.find_by_name('Public')
      end
    end

    def run_before_save
      if (file_content_type == 'audio/mpeg') || (file_content_type == 'audio/mp3')
        self.audio_length = Mp3Info.open(Paperclip.io_adapters.for(file).path).length.round
      end
    end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  load_and_authorize_resource

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.unscoped.order('updated_at DESC').paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end
  
  # GET /documents/table
  def table
    @documents = Document.all

    respond_to do |format|
      format.html { render :layout => 'layouts/application-fluid' } # index.html.erb
      format.json { render json: @documents }
    end
  end
  
  # GET /documents/search?q
  def search
    if params[:q]
      @documents = Document.unscoped.order('updated_at DESC').search(params[:q]).paginate(:page => params[:page], :per_page => 20)
      @count = @documents.count
      
      render 'index'
    else
      redirect_to documents_path
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
    @document.roles << Role.find_by_name('Public')

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])
    @document.user_id = current_user.id

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { respond_with_bip @document }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip @document }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
 
  # GET /documents/1/download
  def download
    @document = Document.find(params[:id])
    # send_file @document.file.to_file, :type => @document.file_content_type
    send_file Paperclip.io_adapters.for(@document.file).path, :type => @document.file_content_type
  end
 
  # GET /documents/1/download_source
  def download_source
    @document = Document.find(params[:id])
    send_file Paperclip.io_adapters.for(@document.source).path, :type => @document.source_content_type
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper

  def document_icon_for(document, options = { :size => :icon })
    sizes = { :icon => '80', :thumb => 100, :small => '200', :medium => '380', :large => '980', :full => '1140' }
    icons = {
      'application/pdf' => 'text/filetype_pdf.png',
      'audio/mp3' => 'audio/filetype_mp3.png',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => 'text/filetype_doc.png'
    }
    link_to image_tag("icons/filetypes/#{icons[document.file_content_type] ? icons[document.file_content_type] : 'extras/filetype_blank.png'}", :width => sizes[options[:size]], :style => 'box-shadow: none; -moz-box-shadow: none; -webkit-box-shadow: none;'), document, :class => 'avatar'
  end

end

app/views/documents/_document.html.haml
.feed_item
  - if can? :read, document
    .floatleft= document_icon_for document, :size => size ||= :thumb
    %h3
      = link_to document.name, document
      %small
        = timeago(document.updated_at)
        ago by
        = link_to document.user.name, document.user
    %p
      - if document.description
        = document.description
        %br
      - if document.author
        authored by
        = document.author
        %br
      - if document.language
        = document.language.name
    %p
      = link_to download_document_path(document), :rel => 'popover-right', :title => 'Download', 'data-content' => "#{document.file_content_type}<hr/>#{((document.audio_length ? "#{document.formatted_audio_length}<br/>" : ' ') + "#{change_units(document.file_file_size)}")}" do
        %i.icon-download-alt
      - if document.source.path
        %i.icon-folder-close{ :rel => 'popover-top', :title => 'Source File Present', 'data-content' => "This file has an attached source file, which may be an editable version of this document. If you would like access to it, please contact your PCVL.<hr/>#{document.source_file_name}<br/>#{document.source_comment}" }
      = mime_icon(document.file_content_type)
      = render document.roles
      = render 'shared/tags', :tags => document.tag_list
  - else
    .alert.alert-info
      - if user_signed_in?
        You do not have access to all documents. If you are a PCV or Staff member, request access #{link_to 'here', volunteer_request_feedback_index_path}.
      - else
        You do not have access to all documents. For greater access privileges, please #{link_to 'login', login_path} as a PCV or staff member.
  %hr.clearfloat

app/views/documents/_fields.html.haml
= f.file_field :file, :label => 'Primary file (currently limited to 30Mb)', :rel => 'popover-right', :title => 'Allowed File Types', 'data-content' => 'The following file types are allowed:<ul><li>mp3</li><li>pdf</li><li>txt</li><li>csv</li><li>xml</li><li>html</li><li>ppt</li><li>xls</li><li>kml</li><li>tex</li><li>swf</li><li>rss</li></ul>'
= f.text_field :name, :rel => 'popover-right-focus', :title => "File Name/Title", 'data-content' => "If you leave this blank, the original file name will be used."
= f.text_field :author, :rel => 'popover-right-focus', :title => "Who created the thing?", 'data-content' => "Give credit where credit is due."
= f.collection_select :language_id, Language.all, :id, :name
= f.text_field :description, :rel => 'popover-right-focus', :title => "Explain yourself!", 'data-content' => "Tell us all about this file, particularly if it's not obvious from the title."
= f.text_field :tag_list, :rel => 'popover-right-focus', :title => "Tag it!", 'data-content' => "Tags are important, because they connect this file to relevant users, pages, case studies, photos, and libraries! Wow, that's a lot."
= f.select :country, allowed_countries
%div{'title' => 'Permissions Help', 'data-content' => "You can restrict access to this document. Keep in mind that these permissions are not hierarchical; if you set it to 'Volunteer' only, PC Staff members will be unable to view it. To restrict a document to PCVs and Staff, check 'Volunteer' and 'Staff' only.", 'rel' => 'popover-left'}
  = f.collection_check_boxes :role_ids, Role.unscoped.order('long_name ASC').all, :id, :long_name, :label => 'Permissions'
%hr
= f.file_field :source, :label => 'Optional source file. This can be a proprietary editable format, and should be included if anyone might need to edit this document in the future.', :rel => 'popover-right', :title => 'What is this?', 'data-content' => 'Source files are original files which may have been used to generate the primary file. A training manual, for example, should be distributed in PDF or eBook format, but the origin might be a Word document. Attach the original here.<hr/>The following file types are allowed:<ul><li>all main file types (hover above)</li><li>doc</li><li>docx</li></ul>'
= f.text_field :source_comment, :label => 'Describe the source document', :rel => 'popover-right-focus', :title => "Why'd you add a source?", 'data-content' => "Details regarding the source file, and why you've attached it, perhaps."

app/views/documents/_form.html.haml
= bootstrap_form_for(@document, :multipart => true) do |f|
  = render 'fields', :f => f
  = f.submit 'Upload it!'
  = f.cancel

app/views/documents/_menu.html.haml
.subnav
  %ul.nav.nav-pills
    %li.dropdown
      %a.dropdown-toggle{'data-toggle' => 'dropdown', 'href' => '#'}
        View by
        %b.caret
      %ul.dropdown-menu
        %li= link_to 'Recently updated', documents_path
        %li= link_to 'Table View', table_documents_path
    %li= link_to 'Upload file', new_document_path if can? :create, Document
    - if user_signed_in? && @document && !@document.new_record?
      %li.dropdown
        %a.dropdown-toggle{'data-toggle' => 'dropdown', 'href' => '#'}
          Actions
          %b.caret
        %ul.dropdown-menu
          %li= link_to 'Add to library', '#new_stack_form_modal', 'data-toggle' => 'modal' if can? :create, Stack
          %li= link_to 'Edit', '#edit_document_form_modal', 'data-toggle' => 'modal' if can? :edit, @document
          %li= link_to 'Delete', '#destroy_document_form_modal', 'data-toggle' => 'modal' if can? :destroy, @document
    - unless params[:action] == 'table'
      = form_tag search_documents_path, :method => :get, :class => 'navbar-form pull-right' do
        = text_field_tag :q, nil, :placeholder => "search within files"
        = submit_tag 'search', :class => 'btn btn-success'

app/views/documents/_stacks_form.html.haml
- stack = @document.stacks.build
= bootstrap_form_for stack do |f|
  = f.hidden_field(:stackable_id)
  = f.hidden_field(:stackable_type)
  = f.collection_select :library_id, Library.order('name ASC').available(@document, (can?(:manage, Document) ? nil : current_user)), :id, :name
  = f.actions do
    = f.submit 'add to library'

app/views/documents/edit.html.haml
.row
  .span3
    = render 'shared/menu'
  .span-7
    = render 'form'
  .span2

app/views/documents/index.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    = render 'menu'
    %section
      %h1 Files
      %ul.feed
        = render @documents
      .center= will_paginate
  .span2
    .box
      %h3 Top Document Tags
      = cloud_of_tags

app/views/documents/new.html.haml
.container
  .row
    .span3
      = render 'shared/menu'
    .span9
      = render 'menu'
      .row
        .span4.offset1
          .well
            %h2 Upload a file
            = render 'form'
        .span4
          .well
            %h2 Suggested Tags
            %p The following tags have been used on more than 2 files already; consider using them to maintain consistency.
            %hr
            - for tag in Document.tag_counts.order('name ASC') do
              - if Document.tagged_with(tag.name).count > 2 || Page.tagged_with(tag.name).count > 2
                = tag.name
                %br

app/views/documents/show.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    = render 'menu'
    %h1
      = @document.name
    %hr
    %p= best_in_place_if can?(:update, @document), @document, :description
    %p
      - if @document.author
        author:
        = @document.author
        %br
      - if @document.language
        language:
        = @document.language.name
    %p
      = link_to '#bitly_url_qrcode', 'data-toggle' => 'modal' do
        %i.icon-qrcode{ :rel => 'popover-top', :title => 'Get a QR Code', 'data-content' => "<h3>What's a QR Code?</h3>QR Codes are 3-dimensional barcodes which can be scanned by smartphones and used to store URLs. This link will take you to a QR Code image you can use online or in print to represent this document." }
      = link_to '#bitly_url', 'data-toggle' => 'modal' do
        %i.icon-resize-small{ :rel => 'popover-top', :title => 'Get a shortened URL', 'data-content' => "<h3>Why should I care?</h3>URLs can be long. Just take a look up in your address bar. If you want to Tweet this URL, post it somewhere, or just save space, you can use this one instead. Click to retrieve it." }
      - if can? :read, @document    
        = link_to download_document_path(@document), :rel => 'popover-top', :title => 'Download', 'data-content' => "#{@document.file_file_name}<br/>#{@document.file_content_type}<hr/>#{((@document.audio_length ? "#{@document.formatted_audio_length}<br/>" : ' ') + "#{change_units(@document.file_file_size)}")}" do
          %i.icon-download-alt
          download
      = mime_icon(@document.file_content_type)
      = change_units(@document.file.size)
      = render @document.roles
      = render 'shared/tags', :tags => @document.tag_list
      - if @document.source.path
        %br
        %i.icon-folder-close{ :rel => 'popover-top', :title => 'Source File Present', 'data-content' => "This file has an attached source file, which may be an editable version of this document. If you would like access to it, please contact your PCVL.<hr/>#{@document.source_file_name}<br/>#{@document.source_comment}" }
        = link_to 'download source', download_document_path(@document, :file => :source), :rel => 'popover-top', :title => 'Warning!', 'data-content' => "By downloading this file, you are taking on the burden of responsibility for its contents. DO NOT redistribute it indiscriminatlely. It is to be used to update the PDF or otherwise static version hosted here for redistribution." if can? :download_source, @document
        = @document.source.content_type
        = change_units @document.source.size
        = mime_icon(@document.source.content_type)
    .well
      - if @document.stacks.any?
        %h3 Libraries containing this file
        %ul
          - @document.stacks.each do |s|
            %li #{link_to s.library.name, s.library if s.id} #{button_to 'remove', s, :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger', :style => 'display:inline-block;' if can? :destroy, s}
      = link_to 'Add to a library', '#new_stack_form_modal', 'data-toggle' => 'modal', :class => 'btn btn-success' if can? :create, Stack
      = link_to 'Create a library', new_library_path, :class => 'btn btn-primary' if can? :create, Library
    %hr
    :erb
      <div id="disqus_thread"></div>
      <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'pcsenegal'; // required: replace example with your forum shortname
        // turn on dev mode for dev/test env
        var disqus_developer = <%= Rails.env.production? ? 0 : 1 %>;
        // identify current page
        var disqus_identifier = "document-<%= @document.id %>";
        // identify current url
        var disqus_url = "<%= document_url(@document) %>";
        // set the thread title
        var disqus_title = "<%= @document.canonical_title %>";
        // set the category to pages
        var disqus_category_id = '1483651';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

  .span2
    = document_icon_for @document, :size => :small
    .box
      %h3 Top Document Tags
      = cloud_of_tags
= render 'shared/modal_standard', :id => "bitly_url", :title => 'Bit.ly Shortened URL', :body => raw("<p>#{shorten_url(document_url(@document))}<p>#{link_to 'Why is this not a link?', '/help#shortlinks'}</p>"), :footer => nil
= render 'shared/modal_standard',:id => "bitly_url_qrcode", :title => 'QR Code', :body => image_tag(shorten_url(document_url(@document), :qr, :medium => 'qrcode')) + raw("<p>#{link_to 'What do I do with this?', '/help#qrcodes'}</p>"), :footer => nil
- if can? :create, Stack
  = render 'shared/modal_standard', :id => 'new_stack_form_modal', :title => 'Add to library', :body => render('documents/stacks_form')
- if can? :edit, @document
  = render 'shared/modal_standard', :id => 'edit_document_form_modal', :title => 'Edit file', :body => render('documents/form')
- if can? :destroy, @document
  = render 'shared/modal_standard', :id => 'destroy_document_form_modal', :title => 'Are you sure?', :body => button_to('Delete file', @document, :method => :delete, :class => 'btn btn-danger')

app/views/documents/table.html.haml
.row-fluid
  .span2
    = render 'shared/menu'
  .span10
    = render 'menu'
    %table.table.table-striped.table-condensed.dyn-datatable
      %thead
        %th
        %th Name
        %th Description
        %th Last Updated
        %th Author
        %th Language
        %th Tags
        %th Size
        %th Permissions
        %th Source?
        %th
      %tbody
        - @documents.each do |document|
          %tr
            %td= link_to 'view', document
            %td= best_in_place_if can?(:update, document), document, :name
            %td= best_in_place_if can?(:update, document), document, :description
            %td
              = time_ago_in_words(document.updated_at)
              ago by
              = link_to document.user.name, document.user
            %td= best_in_place_if can?(:update, document), document, :author
            %td= document.language.name if document.language
            %td= best_in_place_if can?(:update, document), document, :tag_list
            %td
              = document.file.size
              bytes
            %td= render document.roles
            %td
              - if document.source.path
                %i.icon-ok.tooltip-top{:title => document.source_file_name}
            %td
              - if can? :read, document
                = link_to download_document_path(document) do
                  download
              %br
              = document.file_content_type
              -#= mime_icon(document.file_content_type)
    .clearfloat