config/routes.rb
OmniauthDemo::Application.routes.draw do

  #get "tag/index"

  require 'resque/server'

  authenticate 'user' do
    mount Resque::Server.new, :at => '/resque'
  end

  resources :tags, :only => [ :index ]

  resources :ticket_updates, :priorities

  resources :ticket_owners

  resources :ticket_codes

  resources :ticket_categories

  resources :site_configs, :except => [ :new, :create, :destroy, :show ]

  Mercury::Engine.routes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
  end
  
  resources :users, :only => [ :index, :show, :edit, :update, :destroy ] do
    collection do
      get :search
      get :table
    end
    resources :tickets, :except => [ :edit ]
  end

  resources :documents, :path => 'files' do
    member do
      get :download
    end
    collection do
      get :search
      get :table
    end
  end

  resources :case_studies do
    collection do
      get :added
      get :updated
      get :search
      get :table
    end
    member do
      post :mercury_update
    end
  end

  resources :imports do
    member do
      get 'process_yaml'
    end
  end

  resources :languages

  resources :libraries do
    member do
      get :download
      get :podcast, :as => :podcast, :defaults => { :format => 'xml' }
    end
    collection do
      get :search
    end
  end

  resources :stacks, :only => [ :index, :new, :create, :destroy ]

  resources :photos do
    collection do
      get :search
    end
    member do
      get :embed
    end
  end

  resources :sites, :sectors, :positions, :jobs, :staff, :websites, :identities, :stages, :scopes, :regiontypes, :pc_regions, :regions, :volunteers, :moments

  resources :blogs do
    collection do
      get :updated
    end
  end

  resources :feedback, :except => [:edit, :update] do
    collection do
      get :volunteer_request
    end
  end

  resources :contributions, :only => [ :index, :new, :create, :destroy ]

  resources :permissions, :only => [ :index, :new, :create, :destroy ]

  resources :pages do
    collection do
      get :updated
      get :added
      get :popular
      get :ajax
      get :search
      get :feed, :as => :feed, :defaults => { :format => 'atom' }
      get :table
    end
    member do
      post :mercury_update
    end
  end

  match '/disclaimer', :to => 'statics#disclaimer', :as => :disclaimer
  match '/privacy', :to => 'statics#privacy', :as => :privacy_policy
  match '/security', :to => 'statics#security', :as => :security
  match '/about_us', :to => 'statics#about_us', :as => :about
  match '/splash', :to => 'statics#splash', :as => :splash
  match '/help', :to => 'statics#help', :as => :help
  match '/search', :to => 'statics#search', :as => :search
  match '/welcome', :to => 'statics#welcome', :as => :entry
  match '/goodbye', :to => 'statics#goodbye', :as => :exit
  match '/dashboard', :to => 'statics#dashboard', :as => :dashboard
  match '/timeline', :to => 'statics#timeline', :as => :timeline

  match '/feedback', :to => 'feedback#new'
  match '/feed/pages', :to => 'pages#updated'
  
  match '/facebook' => redirect('https://apps.facebook.com/peacecorps')
  match '/youtube' => redirect('https://www.youtube.com/pcsenegaladmin')
  match '/twitter' => redirect('http://twitter.com/#!/pc_senegal')
    
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'statics#splash'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  skip_authorization_check

  def dashboard
    redirect_to root_path unless cookies[:splashed] == 'viewed'
    @users = User.unscoped.order('users.updated_at DESC').limit(5)
    @pages = Page.order('pages.updated_at DESC').limit(10)
    @case_studies = CaseStudy.order('updated_at DESC').limit(10)
    @photos = Photo.unscoped.order('updated_at DESC').limit(20).all
    @documents = Document.unscoped.order('updated_at DESC').limit(10).all
  end

  def splash
    @title = 'Splash'
    cookies[:splashed] = 'viewed'

    @slides = []
    Photo.order('updated_at DESC').tagged_with('splash', :on => :settings).each do |p|
      @slides << {:title => p.title, :text => p.description, :photo => p.photo.url(:wide), :link => 'view photo', :path => p} if p.photo
    end
    Page.order('updated_at DESC').tagged_with('splash', :on => :settings).each do |p|
      @slides << {:title => p.title, :text => p.description, :photo => p.photo.photo.url(:wide), :link => 'read more', :path => p} if p.photo
    end
    CaseStudy.order('updated_at DESC').tagged_with('splash', :on => :settings).each do |cs|
      @slides << {:title => cs.title, :text => cs.summary, :photo => cs.photo.photo.url(:wide), :link => 'go to case study', :path => cs} if cs.photo
    end

    @spotlights_small = []
    Photo.order('updated_at DESC').tagged_with('spotlight_small', :on => :settings).each do |p|
      @spotlights_small << {:title => p.title, :text => p.description, :photo => p.photo.url(:spotlight), :path => p} if p.photo
    end
    Page.order('updated_at DESC').tagged_with('spotlight_small', :on => :settings).each do |p|
      @spotlights_small << {:title => p.title, :text => p.content, :photo => p.photo.photo.url(:spotlight), :path => p} if p.photo
    end
    CaseStudy.order('updated_at DESC').where('photo_id IS NOT NULL', :on => :settings).tagged_with('spotlight_small').each do |cs|
      @spotlights_small << {:title => cs.title, :text => cs.summary, :photo => cs.photo.photo.url(:spotlight), :path => cs} if cs.photo
    end
    Library.order('updated_at DESC').tagged_with('spotlight_small', :on => :settings).each do |lib|
      if lib.photos.any?
        @spotlights_small << {:title => lib.canonical_title, :text => lib.description, :photo => lib.photos.first.photo.url(:spotlight), :path => lib}
      end
    end
    
    @spotlights_large = []
    Photo.order('updated_at DESC').tagged_with('spotlight_large', :on => :settings).each do |p|
      @spotlights_large << {:title => p.title, :text => p.description, :photo => p.photo.url(:spotlight), :path => p} if p.photo
    end
    Page.order('updated_at DESC').tagged_with('spotlight_large', :on => :settings).each do |p|
      @spotlights_large << {:title => p.title, :text => p.content, :photo => p.photo.photo.url(:spotlight), :path => p} if p.photo
    end
    CaseStudy.order('updated_at DESC').where('photo_id IS NOT NULL', :on => :settings).tagged_with('spotlight_large').each do |cs|
      @spotlights_large << {:title => cs.title, :text => cs.summary, :photo => cs.photo.photo.url(:spotlight), :path => cs} if cs.photo
    end
    Library.order('updated_at DESC').tagged_with('spotlight_large', :on => :settings).each do |lib|
      if lib.photos.any?
        @spotlights_small << {:title => lib.canonical_title, :text => lib.description, :photo => lib.photos.first.photo.url(:spotlight), :path => lib}
      end
    end

    respond_to do |format|
      format.html { render 'splash', :layout => 'splash' }
    end
    
  end

  def help
    @title = 'Help'
  end

  def about_us
    @title = 'About us'
  end

  def disclaimer
    @title = 'Disclaimer'
  end

  def privacy
    @title = 'Privacy Policy'
  end

  def security
    @title = 'Security'
  end
  
  def search
    @title = 'Search'
    if params[:q].present? && params[:resource] == 'all'
      @results = Search.new(params[:q]).paginate(:per_page => 50)
      redirect_to @results.first if @results.count == 1
    elsif params[:q].present?
      @results = Search.new(params[:q]).paginate(:per_page => 50)
      redirect_to @results.first if @results.count == 1
    end
  end

  def welcome
    authorize! :read, :welcome
  end

  def goodbye
    
  end

  def timeline
    @title_photo = Photo.tagged_with('timeline_splash').first
    unless request.user_agent =~ /MSIE/
      render 'timeline', :layout => nil
    else
      redirect_to moments_path
    end
  end

end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_help_menu.html.haml
.subnav
  %ul.nav.nav-pills
    %li= link_to "Case Studies", '#case_studies'
    %li= link_to "Content", '#content'
    %li= link_to "Files", '#files'
    %li= link_to "Libraries", '#libraries'
    %li= link_to "Photos", '#photos'
    %li= link_to "Staff", '#staff'
    %li= link_to "Users", '#users'
    %li= link_to "Volunteers", '#volunteers'
    %li= link_to "QR Codes", '#qrcodes'
    %li= link_to 'Shortlinks', '#shortlinks'

app/views/statics/_menu.html.haml
.subnav
  %ul.nav.nav-pills
    %li= link_to 'Disclaimer', disclaimer_path
    %li= link_to 'Privacy policy', privacy_policy_path
    %li= link_to 'Help!', help_path
    %li= link_to 'Security', security_path
    %li= link_to 'About us', about_path
    = render 'shared/search' unless params[:action] == 'table'

app/views/statics/about_us.html.haml
.row
  .span3
    = render 'shared/menu'
  .span9
    .hero-unit
      %h1= @title
      %p This site is running a web app developed by Peace Corps Senegal's PCV Jack Brown. It's written in Ruby/Rails, designed from the ground up tailor-made to fit the needs of an active Peace Corps Post.
      %p Over here at Peace Corps Senegal, we pride ourselves on being at the forefront when it comes to integrating technology with work, which is why we're pleased to host this new site offering support not just to the PC Senegal community, but any and all posts which choose to use it.
      %p For more info, please contact Jack directly at jack@brownjohnf.com.
      %p Welcome, and enjoy your stay!

app/views/statics/dashboard.html.haml
.row
  .span3
    = render 'shared/menu'
  .span9
    .tabbable
      %ul.nav.nav-pills
        %li.active= link_to "Pages (#{Page.count})", '#pages', 'data-toggle' => 'tab'
        %li= link_to "Files (#{Document.count})", '#files', 'data-toggle' => 'tab'
        %li= link_to "Users (#{User.count})", '#users', 'data-toggle' => 'tab'
        %li= link_to "Case Studies (#{CaseStudy.count})", '#case_studies', 'data-toggle' => 'tab'
        %li= link_to 'News', '#news', 'data-toggle' => 'tab'
        %li= link_to 'Statistics', '#stats', 'data-toggle' => 'tab'
        %li= link_to 'Tags', '#tags', 'data-toggle' => 'tab'
        %li= link_to "Photos (#{Photo.count})", '#photos', 'data-toggle' => 'tab'
      .tab-content
        .tab-pane#pages.active
          %h1 Latest Page Updates
          %ul.feed
            = render @pages, :size => :icon
        .tab-pane#files
          %h1 Files
          %ul.feed
            = render @documents, :size => :icon
        .tab-pane#users
          %h1 Users
          %ul.feed
            = render @users, :size => :icon
        .tab-pane#case_studies
          %h1 Case Studies
          %ul.feed
            = render @case_studies, :size => :icon
        .tab-pane#news
          .row-fluid
            .span6
              = image_tag 'twitter_newbird_blue.png', :class => 'twitter_bird'
              = render 'shared/twitter', :twitter_user => 'pc_senegal'
            .span6
              = image_tag 'twitter_newbird_blue.png', :class => 'twitter_bird'
              = render 'shared/twitter', :twitter_user => 'stompoutmalaria'
        .tab-pane#stats
          %h1 Quick Stats
          %ul
            %li= pluralize(User.count, 'user')
            %li= pluralize(Page.count, 'page')
            %li= pluralize(CaseStudy.count, 'case study')
            %li= pluralize(Photo.count, 'photo')
            %li= pluralize(Document.count, 'file')
            %li= pluralize(Library.count, 'library')
            %li= pluralize(Blog.count, 'blog')
            %li
              - total_resources = User.count + Page.count + CaseStudy.count + Photo.count + Document.count + Blog.count
              = pluralize(total_resources, 'resource')
              and counting!
              %br
              that's
              %strong= pluralize((total_resources - User.count) / (User.count > 0 ? User.count : 1), 'resource')
              per user!
          %h1 Most complete profiles
          %ul
            - REDIS.zrevrange('users:stats:perc_profile', 0, 9).each do |user_id|
              %li= link_to REDIS.hget("users:#{user_id}", 'name'), user_path(user_id)
          %h1 Least complete profiles
          %ul
            - REDIS.zrange('users:stats:perc_profile', 0, 9).each do |user_id|
              %li= link_to REDIS.hget("users:#{user_id}", 'name'), user_path(user_id)
        .tab-pane#tags
          %h1 Top Tags
          .well
            = cloud_of_tags Photo
            = cloud_of_tags Document
            = cloud_of_tags Page
            = cloud_of_tags CaseStudy
            = cloud_of_tags User
            = cloud_of_tags Blog
        .tab-pane#photos
          %h1 Latest Photos
          = render @photos

app/views/statics/disclaimer.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    .hero-unit
      %h1= @title
      %p The contents of this web site do not reflect in any way the positions of the U.S. Government or the United States Peace Corps. This web site is managed and supported by Peace Corps Volunteers and our supporters. It is not a U.S. Government web site.
  .span2

app/views/statics/goodbye.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    %h1 Goodbye
    %p Thanks for stopping by! Don't forget to check back soon for the latest news and information from Peace Corps #{country}!
  .span2

app/views/statics/help.html.haml
.row
  .span3
    = render 'shared/menu'
  .span9.anchor-hop
    %h1 Help & Documentation
    = render 'help_menu'
    %p Welcome to the Help Me! page. Jack has written all of this, and therefore it's probably filled with silliness. If you'd like to contribute, get in touch: jack@brownjohnf.com.
    %section#case_studies
      %h2 Case Studies
      %hr
      %h4 What's a case study?
      %p Case studios are a way for you to document the work you've done, not only for the edification of future generations of PCVs, but also for your resumé. You can link to them on a resume, print them and attach them (old school), or simply refer a potential employer to your profile.
    %section#content
      %h2 Content/Pages
      %hr
      %h4 What's a page?
      %p Pages are a sort of wiki combined with a tradional website. They allow us to host reference material for PCVs and staff, but also show the rest of the world what we're up to. They should always be crisp and professional, and are NOT a place for case studies or any other personal information. Before creating a page, think long and hard about why you're making it, whether your information could better be combined with an existing page, and write it professionally.
    %section#files
      %h2 Files
      %hr
    %section#libraries
      %h2 Libraries
      %hr
    %section#photos
      %h2 Photos
      %hr
    %section#staff
      %h2 Staff
      %hr
    %section#users
      %h2 Users
      %hr
    %section#volunteers
      %h2 Volunteers
      %hr
    %section#shortlinks
      %h2 Shortlinks
      %hr
      %p Shortlinks are currently available for the following resources:
      %ul
        %li Files
        %li Libraries
        %li Pages
      %h4 What are they?
      %p Take a look at a couple of the URLs this app generates:
      %ul
        %li http://www.pcsenegal.org/pages/104-bi-weekly-food-security-update
        %li http://www.pcsenegal.org/pages/178-overview-of-food-security-grant-application-process
      %p Those are a mouthful, huh? Now, imagine you want to tweet or post these URLs. Or maybe put them in an email. Or tattoo them on some tiny piece of your body. It'd be a challenge, wouldn't it? (Actually, for a tattoo I'd recommend a #{link_to 'QR code', '#qrcodes'}.) Shortlinks take those long URLs and turn them into these:
      %ul
        %li http://bit.ly/JOnp0E
        %li http://bit.ly/IEdCYy
      %p Believe it or not, those are the same as the ones above. Well, actually, there <em>better</em> than the ones above, because they also include info for Google Analytics which lets us know how many people used those URLs instead of the long ones.
      %h4 How do I use them?
      %p
        Easy! Just look for the
        %i.icon-resize-small
        icon and click on it. A modal window will drop down with your shortened link. Use at will.
      %h4 Why isn't it a link I can click on/copy easily?
      %p Modern browsers are smart enough to automatically decode bit.ly shortened URLs. To retain its value, you need to copy it manially. Sorry.
      %h4 Why should I care?
      %p Maybe you shouldn't. No, seriously. If you're just posting something on your Facebook wall, use whatever you want. Obviously, if <em>you</em> are the one clicking the link (like you're saving it for later) there's no point in shortening it. BUT, if you're running a campaign, or just curious about how many people are clicking your link, use the shortcode, and shoot your site admins an email. They'll be able to tell you. Cool, huh?
      %h4 I want to build my own campaign URL
      %p Nice. You should. Use this: #{link_to 'Google Campaign URL Builder', "http://support.google.com/googleanalytics/bin/answer.py?hl=en&answer=55578"}.
    %section#qrcodes
      %h2 QR Codes
      %hr
      %p QR codes are currently available for the following resources:
      %ul
        %li Files
        %li Libraries
        %li Pages
      %h4 What are they?
      %blockquote
        .floatright= image_tag "http://bit.ly/JY1vYV.qrcode", :rel => 'popover-left', :title => 'This is a QR code', 'data-content' => "This is the QR code for this page (http://www.pcsenegal.org/help#qrcodes). All I've done is embed an image with this URL: http://bit.ly/JY1vYV.qrcode."
        QR Codes storing addresses and Uniform Resource Locators (URLs) may appear in magazines, on signs, on buses, on business cards, or on almost any object about which users might need information. Users with a camera phone equipped with the correct reader application can scan the image of the QR Code to display text, contact information, connect to a wireless network, or open a web page in the telephone's browser. This act of linking from physical world objects is termed hardlinking or object hyperlinking. QR Codes may also be linked to a location to track where a code has been scanned. Either the application that scans the QR Code retrieves the geo information by using GPS and cell tower triangulation (aGPS) or the URL encoded in the QR Code itself is associated with a location. (courtesy of Wikipedia)
      %h4 Why would I use them?
      %p For PCVs and Staff members, there's not a great deal of practical application for these little guys. To be useful, most PCVs/Staff would need camera phones, and be reading links distributed on printed materials.
      %p However, any document you're creating for distribution outside the PC Post, it's advisable to slap one on it, because their use is expanding rapidly in the States. The CED Newsletter is considering including a QR code in their next issue. Stay tuned.
      %h4 How do I use them?
      %p Luckily for you, most of the work is done. The basic process for a quality QR Code is:
      %ol
        %li Determine what URL you want to encode. Call it URL A.
        %li Append a Google Analytics tracking string to the end, so you know that traffic generated by the QR code is coming from the QR code. Call this URL B.
        %li Run the whole smear (URL B) through a shortening service (this app uses Bit.ly). This will give you URL C.
        %li Turn URL C into a QR Code using a service online; if you've used Bit.ly, just append '.qrcode' to the URL. This is URL D, and is actuall pointing to a .png (Your QR code!)
      %p
        I know, sounds like a lot of work, doesn't it? Don't worry, this app will do all the heavy lifting for you! Just visit the resource you want to encode, and click the
        %i.icon-qrcode
        icon. There's the image. Download it and do as you like with it. It's really that easy.
      %h4 I want to know exactly how many people are scanning my QR code
      %p What a fantastic idea! You're a thinker. To get that info, you need to create a custom Google Analytics (which your admin already runs on the site, most likely) campaign code. Stay tuned for info. In the meantime, talk to Jack.
      %p Okay, Jack, that's great, but I want to embed my QR code in an email! Oh dear. That's going to require an HTML email, which is something we'll cover elsewhere. Stay tuned.

app/views/statics/privacy.html.haml
.container
  .row
    .span3
      = render 'shared/menu'
    .span7
      .hero-unit
        %h1= @title
        %p We will never give, sell, or in any way communicate any personal information to anyone, save with the owner of said information's permission, with the following exceptions:
        %ol
          %li If you are a Peace Corps Volunteer/staff member, your contact information will be shared with other signed in PCVs/staff.
    .span2

app/views/statics/search.html.haml
.container
  .row
    .span3
      = render 'shared/menu'
    .span9
      = render 'menu'
      - if @results
        - if @results.count > 0
          .alert.alert-info Each entry below represents one hit on your query in the resource. You may see multiple copies of the same resource.
          = render @results
        - else
          %h2 Your search returned no results.
        .well
          %h1 Still can't find it? Try Google.
          :erb
            <form class="form-inline" method="get" action="http://www.google.com/search">
              <input type="hidden" name="ie" value="UTF-8" />
              <input type="hidden" name="oe" value="UTF-8" />
              <input type="hidden" name="domains" value="http://www.pcsenegal.org" />
              <input type="hidden" name="sitesearch" value="http://www.pcsenegal.org" checked />
              <!--<input type="submit" name="btnG" value="Google Search" height="50px" />-->
              <input class="span6" id="google_search_input" type="text" name="q" maxlength="200" placeholder="Search pcsenegal.org using Google Search" />
              <button class="btn btn-success" type="submit">Search</button>
            </form>
      - else
        .hero-unit.hero-unit-success
          %p Use the search box above to search for content, case studies, files, people, libraries, and photos. If your search returns only one hit, you'll automatically be redirected to the result.

app/views/statics/security.html.haml
.container
  .row
    .span3
      = render 'shared/menu'
    .span7
      .hero-unit
        %h1= @title
        %p We take privacy and security seriously, and every effort has been made to protect your personal information. For more information please view our #{link_to 'privacy policy', '/privacy'}.
        %p This website uses redundant, 99.999999999% durable storage, and is therefore a reliable way to store institutional memory.
    .span2

app/views/statics/timeline.html.haml
- @timeline_title = SiteConfig.find_by_name('timeline_title').setting + ': ' + SiteConfig.find_by_name('timeline_subtitle').setting
:erb
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <title><%= title + ' | ' + @timeline_title %></title>
      <meta name="description" content="Template Description">
      
      <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

      <style>
        html, body {
          height: 100%;
          padding: 0px;
          margin: 0px;
        }
        #timeline-embed{
          height: 90% !important;
          margin:0px !important;
          border:0px solid #CCC !important;
          padding:0px !important;
          -webkit-border-radius:0px !important;
          -moz-border-radius:0px !important;
          border-radius:0px !important;
          -moz-box-shadow:0 0px 0px rgba(0, 0, 0, 0.25) !important;
          -webkit-box-shadow:0 0px 0px rgba(0, 0, 0, 0.25) !important;
          box-shadow:0px 0px 0px rgba(0, 0, 0, 0.25) !important;
        }
        
        #header {
          font-family: 'Georgia', Times New Roman, Times, serif;
          height: 10%;
        }
        #title {
          margin: 0;
          text-align: center;
        }

        #header a {
          color: #0088CC;
          text-decoration: none;
        }
        #header a:hover {
          color: #005580;
          text-decoration: underline;
        }
        
      </style>
      
    </head>

    <body>
    <div id="header">
      <h1 id="title"><%= title + ' | ' + @timeline_title %></h1>
      &lang;
      <%= link_to 'back to site', dashboard_path %>
    </div>
      <!-- BEGIN Timeline Embed -->
      <div id="timeline-embed"></div>
      <script type="text/javascript">
          var config = {
          width: "100%",
          height: "100%",
          source: '/moments.json?all=true',
          css: '<%= asset_path 'timeline.css' %>',
          js: '<%= asset_path 'timeline-min.js' %>'
        }
      </script>
      <%= javascript_include_tag 'timeline-embed' %>
      <!--<script type="text/javascript" src="http://veritetimeline.appspot.com/latest/timeline-embed.js"></script>-->
      <!-- END Timeline Embed -->
    </body>
  </html>

app/views/statics/welcome.html.haml
.row
  .span12
    .hero-unit
      %h1 Welcome, #{current_user.name}!
      %h2 What would you like to do now?
    .center
      = form_tag search_path, :method => :get, :class => 'form-inline form-mega' do
        -#= select_tag :resource, options_for_select(['all of it'], 'all'), :class => ''
        = text_field_tag :q, nil, :placeholder => "search the site!"
        = submit_tag 'search', :class => 'btn btn-success'
    - if current_user.pc?
      .center
        = link_to 'Browse all pages', pages_path, :class => 'btn btn-info btn-moron'
        = link_to 'Upload a file', new_document_path, :class => 'btn btn-primary btn-moron'
        = link_to 'Create a case study', new_case_study_path, :class => 'btn btn-success btn-moron'
        = link_to 'Create a new page', new_page_path, :class => 'btn btn-warning btn-moron'
      %h1.center Or, read on for more information...
      %hr
.row
  .span3.offset1
    = render 'shared/menu'
  .span7
    - if current_user.role?(:moderator)
      .alert.alert-warning
        %a.close{'data-dismiss' => 'alert'} &times;
        %h3 You are a moderator!
        %p With great power comes great responsibilty. Always be mindful of your actions, and behave with honor.
    - if current_user.role?(:admin)
      .alert.alert-error
        %a.close{'data-dismiss' => 'alert'} &times;
        %h3 You are an administrator!
        %p With great power comes great responsibilty. Always be mindful of your actions, and behave with honor.
    - if current_user.role?(:volunteer)
      .alert.alert-success
        %a.close{'data-dismiss' => 'alert'} &times;
        %h3 You're a Volunteer!
        %p There's a lot you can do with this new site. You should read the #{link_to 'latest features', '#latest_features'} list below to stay up to date, or catch up on what you've missed if you're just joining. And of course, as always, you can always harrass Jack with questions and feature requests.
    - if current_user.role?(:staff)
      .alert.alert-success
        %a.close{'data-dismiss' => 'alert'} &times;
        %h3 You're a staff member!
        %p There's a lot you can do with this new site. You should read the #{link_to 'latest features', '#latest_features'} list below to stay up to date, or catch up on what you've missed if you're just joining. And of course, as always, you can always harrass Jack with questions and feature requests.
    .alert.alert-info
      %a.close{'data-dismiss' => 'alert'} &times;
      %h2 Where to go from here?
      %p For more detailed information regarding your status on this site, please take a look at your #{link_to 'profile', current_user}.
      %p For an overview of content and updates on the site, you can use your #{link_to 'dashboard', dashboard_path}.

    -# PC features
    -if current_user.pc?
      %h2#latest_features
        Latest Features
        %small Volunteers and Staff
      %ul
        %li Suggested tags! When you're uploading files, you'll see a list of commonly used tags on the right. By selecting from that pool, you'll help keep everything tightly linked.
        %li Include source files with #{link_to 'file uploads', new_document_path}. Have a PDF that might need to be edited later? Include the original MS Office doc, and posterity will thank you. Plus, you can always get it back later, so it's like an archive!
        %li Upload #{link_to 'files', new_document_path} and #{link_to 'photos', new_photo_path} right from your computer! Have something beautiful? Useful? Essential? Upload it straight to the website.
        %li #{link_to 'Create pages', new_page_path} right here! It's as easy as using Microsoft Word! Well, almost... But trust us, it's easy.
        %li Now #{link_to 'create case studies', new_case_study_path} on the website. Stop emailing them to Jack, having him send it back, etc. Just create it here, someone will review it, and you're good to go.

    -# non-PC features
    %h2 Latest Features
    %ul
      %li
        QR Codes! Look for the
        %i.icon-qrcode
        icon throughout the site. Clicking on it will take you to an image you can use to link to documents, pages, libraries, and even the site itself!
      %li There's a brand-new look! Enjoy the site's new appearance.
  .span2