config/routes.rb
OmniauthDemo::Application.routes.draw do

  #get "tag/index"

  require 'resque/server'

  authenticate 'user' do
    mount Resque::Server.new, :at => '/resque'
  end

  resources :tags, :only => [ :index ]

  resources :ticket_updates, :priorities

  resources :ticket_owners

  resources :ticket_codes

  resources :ticket_categories

  resources :site_configs, :except => [ :new, :create, :destroy, :show ]

  Mercury::Engine.routes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
  end
  
  resources :users, :only => [ :index, :show, :edit, :update, :destroy ] do
    collection do
      get :search
      get :table
    end
    resources :tickets, :except => [ :edit ]
  end

  resources :documents, :path => 'files' do
    member do
      get :download
    end
    collection do
      get :search
      get :table
    end
  end

  resources :case_studies do
    collection do
      get :added
      get :updated
      get :search
      get :table
    end
    member do
      post :mercury_update
    end
  end

  resources :imports do
    member do
      get 'process_yaml'
    end
  end

  resources :languages

  resources :libraries do
    member do
      get :download
      get :podcast, :as => :podcast, :defaults => { :format => 'xml' }
    end
    collection do
      get :search
    end
  end

  resources :stacks, :only => [ :index, :new, :create, :destroy ]

  resources :photos do
    collection do
      get :search
    end
    member do
      get :embed
    end
  end

  resources :sites, :sectors, :positions, :jobs, :staff, :websites, :identities, :stages, :scopes, :regiontypes, :pc_regions, :regions, :volunteers, :moments

  resources :blogs do
    collection do
      get :updated
    end
  end

  resources :feedback, :except => [:edit, :update] do
    collection do
      get :volunteer_request
    end
  end

  resources :contributions, :only => [ :index, :new, :create, :destroy ]

  resources :permissions, :only => [ :index, :new, :create, :destroy ]

  resources :pages do
    collection do
      get :updated
      get :added
      get :popular
      get :ajax
      get :search
      get :feed, :as => :feed, :defaults => { :format => 'atom' }
      get :table
    end
    member do
      post :mercury_update
    end
  end

  match '/disclaimer', :to => 'statics#disclaimer', :as => :disclaimer
  match '/privacy', :to => 'statics#privacy', :as => :privacy_policy
  match '/security', :to => 'statics#security', :as => :security
  match '/about_us', :to => 'statics#about_us', :as => :about
  match '/splash', :to => 'statics#splash', :as => :splash
  match '/help', :to => 'statics#help', :as => :help
  match '/search', :to => 'statics#search', :as => :search
  match '/welcome', :to => 'statics#welcome', :as => :entry
  match '/goodbye', :to => 'statics#goodbye', :as => :exit
  match '/dashboard', :to => 'statics#dashboard', :as => :dashboard
  match '/timeline', :to => 'statics#timeline', :as => :timeline

  match '/feedback', :to => 'feedback#new'
  match '/feed/pages', :to => 'pages#updated'
  
  match '/facebook' => redirect('https://apps.facebook.com/peacecorps')
  match '/youtube' => redirect('https://www.youtube.com/pcsenegaladmin')
  match '/twitter' => redirect('http://twitter.com/#!/pc_senegal')
    
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'statics#splash'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/stage.rb
class Stage < ActiveRecord::Base

  has_many :volunteers
  has_many :users, :through => :volunteers
  
  validates :country, :name, :arrival, :swear_in, :cos, :presence => true

end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stages }
    end
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
    @stage = Stage.find(params[:id])
    @title = @stage.name
    
    @users = @stage.users.paginate(:page => params[:page], :per_page => 20)
    @recent = @stage.users.unscoped.order('updated_at DESC').limit(20)

    render 'users/index'
  end

  # GET /stages/new
  # GET /stages/new.json
  def new
    @stage = Stage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stage }
    end
  end

  # GET /stages/1/edit
  def edit
    @stage = Stage.find(params[:id])
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(params[:stage])
    @stage.user_id = current_user.id

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render json: @stage, status: :created, location: @stage }
      else
        format.html { render action: "new" }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stages/1
  # PUT /stages/1.json
  def update
    @stage = Stage.find(params[:id])

    respond_to do |format|
      if @stage.update_attributes(params[:stage])
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage = Stage.find(params[:id])
    @stage.destroy

    respond_to do |format|
      format.html { redirect_to stages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.haml
= form_for(@stage) do |f|
  = render 'shared/form_error', :error => @stage if @stage.errors.any?

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :arrival
    = f.date_select :arrival, :start_year => 1961, :end_year => Time.now.year + 1
  .field
    = f.label :swear_in
    = f.date_select :swear_in, :start_year => 1961, :end_year => Time.now.year + 1
  .field
    = f.label :cos
    = f.date_select :cos, :start_year => 1961, :end_year => Time.now.year + 3
  .field
    = f.label :pc_id
    = f.text_field :pc_id
  .field
    = f.label :country
    = f.country_select(:country, ['SN','GM'])
  .actions
    = f.submit

app/views/stages/edit.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    = render 'form'
  .span2

app/views/stages/index.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    :erb
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Arrival</th>
          <th>Swear-in</th>
          <th>Cos</th>
          <th>PC ID</th>
          <th>Country</th>
          <th></th>
          <th></th>
        </tr>

      <% @stages.each do |stage| %>
        <tr>
          <td><%= link_to stage.name, stage %></td>
          <td><%= stage.arrival %></td>
          <td><%= stage.swear_in %></td>
          <td><%= stage.cos %></td>
          <td><%= stage.pc_id %></td>
          <td><%= Carmen.country_name(stage.country) %></td>
          <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
          <td><%= link_to 'Destroy', stage, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
      </table>
  .span2

app/views/stages/new.html.haml
.row
  .span3
    = render 'shared/menu'
  .span7
    = render 'form'
  .span2

app/views/stages/show.html.haml
.container
  .row
    .span-5
      = render 'shared/menu'
    .span-15
      :erb
        <p>
          <b>Name:</b>
          <%= @stage.name %>
        </p>

        <p>
          <b>Arrival:</b>
          <%= @stage.arrival %>
        </p>

        <p>
          <b>Swear-in:</b>
          <%= @stage.swear_in %>
        </p>

        <p>
          <b>COS:</b>
          <%= @stage.cos %>
        </p>

        <p>
          <b>PC ID:</b>
          <%= @stage.pc_id %>
        </p>

        <p>
          <b>Country:</b>
          <%= Carmen.country_name(@stage.country) %>
        </p>
    .span-4.last
      = render 'shared/right_user_menu'